# Site settings
author: Joseph Hallenbeck
title: Joseph Hallenbeck
email: joe@joehallenbeck.com
description: >
    The blog of all things Joe Hallenbeck. Computer science. Cultural criticism.
    Philosophy. Comics. Drawing. Anything and nothing!
baseurl: "/"
url: "http://joehallenbeck.com"

# Social Accounts
twitter: Lordbowlich
github:  Kynda
linkedin: joseph-hallenbeck-203b1b22
shaarli: http://bowlich.com
piwik_url: piwik.kynda.net
piwik_id: 1

# Build settings
markdown: kramdown
highlighter: rouge
include: ["_pages"]
exclude: ["docker-compose.yml", "README.md", "LICENSE", "_posts/images", "bin"]
gems: ["jekyll-paginate", "jekyll-archives"]

# Paginate Configuration
paginate: 10
paginate_path: "/page/:num"

# Archives Configuration
jekyll-archives:
    enabled: ['year', 'categories', 'tags']
    layout: 'archive'
    permalinks:
        year: '/year/:year/'
        tag: '/series/:name/'
        category: '/category/:name/'
